server:
  port: 8091

api:
  jph: 
    domain: "finnhub.io"
    endpointQuote: "api/v1/quote"
    endpointProfile: "api/v1/stock/profile2"
    token: "cna25cpr01qjv5ip3m4gcna25cpr01qjv5ip3m50"

# https://finnhub.io 
# /api/v1/quote?
# symbol=MSFT&token=cna25cpr01qjv5ip3m4gcna25cpr01qjv5ip3m50

# https://finnhub.io/api/v1/stock/profile2
# ?symbol=AAPL&token=cna25cpr01qjv5ip3m4gcna25cpr01qjv5ip3m50